#ifndef DEFINITIONS_H__

#define DEFINITIONS_H__

#define OK 0
#define USAGE_ERROR 1
#define FILE_ACCESS_ERROR 2
#define NONINTEGER_CONTAINMENTS_ERROR 3
#define EMPTY_FILE_TO_CAT_ERROR 4
#define EMPTY_FILE_TO_SORT_ERROR 5
#define BINFILE_TYPE_ERROR 6
#define WRONG_NUMARG_C_ERROR 7
#define UNKNOWN_ERROR 99

#endif
